-- MySQL Script generated by MySQL Workbench
-- 07/08/16 17:44:18
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema sample_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sample_db` DEFAULT CHARACTER SET utf8mb4 ;
USE `sample_db` ;

-- -----------------------------------------------------
-- Table `sample_db`.`samples`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sample_db`.`samples` ;

CREATE TABLE IF NOT EXISTS `sample_db`.`samples` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `name` VARCHAR(128) NOT NULL COMMENT '名前',
  `age` INT(3) NOT NULL COMMENT '年齢',
  `birthday` DATE NOT NULL COMMENT '誕生日',
  `created` DATETIME NOT NULL COMMENT '作成日時',
  `modified` DATETIME NOT NULL COMMENT '更新日時',
  `delete_flg` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '削除フラグ（false..有効、true..削除）',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = 'サンプル';


-- -----------------------------------------------------
-- Table `sample_db`.`admin_users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sample_db`.`admin_users` ;

CREATE TABLE IF NOT EXISTS `sample_db`.`admin_users` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `name` VARCHAR(128) NOT NULL COMMENT '名前',
  `email` VARCHAR(256) CHARACTER SET 'ascii' COLLATE 'ascii_bin' NOT NULL COMMENT 'メールアドレス（UK...767 bytesの制約のためascii_bin）',
  `password` VARCHAR(256) BINARY NOT NULL COMMENT 'パスワード（暗号化済み）',
  `created` DATETIME NOT NULL COMMENT '作成日時',
  `modified` DATETIME NOT NULL COMMENT '更新日時',
  `delete_flg` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '削除フラグ（false..有効、true..削除）',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB
COMMENT = '管理ユーザ';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
